### ISSUE TITLE
Permitir CSS externo mediante la generación de una DIV pura (en html_str())

### ISSUE THREAD

**Issue by arielmol** [SAT-CFDI/python-satcfdi#11]
Actualmente la generación de HTML genera todo el HTML incluyendo  `<html> `, `<head> `con su CSS y `<body>`. Lo cual funciona bien para un caso básico.

Si un usuario requiere incrustar el HTML en una paǵina propia, o bien si quiere generar un estilo propio es difícil integrarlo ya que debe cargarse, separarse, y modificar el DOM HTML a mano o hacer truculencias de regexes.

Sería más conveniente generar sólo el `<div>` y nada de CSS (pero mantener la clases puestas), de esa manera el HTML se vuelve mucho más flexible y tendría las siguientes ventajas:

 - Se puede embeber en cualquier proyecto
 - Se puede crear CSS propio
 - Se puede generar el PDF usando herramientas como wkhtmltopdf.
 - Se pueden generar divs en masa para crear un html masivo, y luego usar herramientas como wkhtmltopdf para generar un PDF gigante de muchos cfdi de un solo golpe

En resumen la sugerencia es crear un generador sólo del `<div>` y de esa manera la cadena se incrusta directo en cualquier HTML que tenga el usuario, y el mismo usuario decidirá qué CSS quiere usar para las clases que la función retorne: Algo así:

```python
div = invoice.html_div_str()
```

O así:
```python
div = invoice.html_str( onlydiv=True )
```

La sugerencia es muy fácil de implementar, ya que actualmente se genera todo el HTML, es cosa de reducirlo.

**Comment by arielmol** [comment]
Analizando un poco, todo se podría solucionar simplemente cambiando `<body>` por `<div>` y colocando una clase particular:
```html
....
<body>
  <h3>CFDI de Ingreso</h3>
  <table>
    <tr>
      <th style="width: 10%">Serie</th>
      <th style="width: 10%">
        Folio</th>
....
```

Algo así:

```html
....
<div class="satcfdi">
  <h3>CFDI de Ingreso</h3>
  <table>
    <tr>
      <th style="width: 10%">Serie</th>
      <th style="width: 10%">
        Folio</th>
....
```

Y con eso un el usuario final que podría usar cosas así para darle su estilo propio:
```css
    .satcfdi {
      font-family: Arial;
      font-size: 9pt;
    }
    .satcfdi > h3 {
      margin-top: -10px;
      margin-bottom: 0px;
      font-size: 9.89pt;
      background-color: #333;
      padding-top: 3px;
      padding-bottom: 3px;
      text-align: center;
      color: white;
      letter-spacing: 4px;
      font-weight: bold;
    }
...
```
